# Generated by Django 4.2.3 on 2023-08-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seating_number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=256)),
                ("student_case", models.SmallIntegerField()),
            ],
        ),
    ]
