# Generated by Django 4.2.3 on 2023-08-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="degree",
            name="total_degree",
            field=models.FloatField(default=410),
        ),
    ]
