# Generated by Django 4.2.3 on 2023-08-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0002_degree_total_degree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degree",
            name="seating_number",
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
