# Generated by Django 4.2.3 on 2023-08-01 22:17

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("degree", "0003_alter_degree_seating_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="degree",
            name="vector_column",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="degree",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["vector_column"], name="degree_degr_vector__5cd97e_gin"
            ),
        ),
    ]
